apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mb1u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mb1u
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mb1u
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mb1u
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mb1u
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dtqb-tenant/rhtap-demo-app/hacbs-test-project-mb1u@sha256:79bb47c472e3677d2f791c91c68c1a1288913550b349fdef57328320ba8c289c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
