apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mb1u
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dtqb-tenant/rhtap-demo-app/hacbs-test-project-mb1u@sha256:79bb47c472e3677d2f791c91c68c1a1288913550b349fdef57328320ba8c289c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
