apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mb1u
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dtqb-tenant/rhtap-demo-app/hacbs-test-project-mb1u@sha256:d7db4b94b0157773e3cf5c344c2c65b26b7273a1aadf4f208fdeeb08a4cb2d48
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
